## Gryphon T/P Sessions Python Phase II Day 1

In [ ]:
a=int(input("Enter a number: "))
b=int(input("Enter a number: "))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

In [ ]:
l=[10,20,30,"KDK","Nagpur",]
key=eval(input("Enter the Value to find:"))
f=False
for i in l:

    if (i==key):
        f=True
        break
    else:
        f=False

if f :
    print("found it")

else :
    print("not found")

not found


In [12]:
a=int(input("Enter a Number:"))
i=10
while(i>=1):
    print(f"{a} x {i} = {a*i}")
    i-=1

print()
print()
a=int(input("Enter a Number:"))
i=0
while(i<=10):
    print(f"{a} x {i} = {a*i}")
    i+=1




20 x 10 = 200
20 x 9 = 180
20 x 8 = 160
20 x 7 = 140
20 x 6 = 120
20 x 5 = 100
20 x 4 = 80
20 x 3 = 60
20 x 2 = 40
20 x 1 = 20


10 x 0 = 0
10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100


In [ ]:
import numpy as np
# print(np.__version__)
#to check version of numpy installed

# to create 1d array
n1 = np.array([1, 2, 3, 4, 5])

# to create 2d array
n2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# printing dimention of array
print(n1.ndim)
print(n2.ndim)
print()


# printing shape of array
print(n1.shape)
print(n2.shape)
print()


#  to create a array from given ranges(start,stop,step) we can use
# arrange()
n3=np.arange(25)
print(n3)
print()


# ones()
# it gives arrays to 1'set
n4=np.ones((3,4),dtype=int)
print(n4)
print()
# similarly zeros()
# it gives arrays of zero

n5=np.zeros((3,4),dtype=int)
print(n5)

1
2

(5,)
(2, 3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
